manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: custom-zephyr
      url-base: https://github.com/helo9
  projects:
    - name: zephyr
      remote: custom-zephyr
      revision: st-half-duplex-uart
      import: true
    - name: jMAVSim
      remote: custom-zephyr
      revision: zephyr
      path: modules/sim/jMAVSim
      submodules: true
  self:
    path: zephly
