manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: private
      url-base: https://github.com/helo9
  projects:
    - name: zephyr
      remote: private
      revision: st-half-duplex-uart
      import: true
    - name: jMAVSim
      remote: private
      revision: zephyr
      path: modules/sim/jMAVSim
      submodules: true
    - name: c_library_v2
      remote: private
      revision: zephyr
      path: modules/sim/mavlink
  self:
    path: zephly
