manifest:
  remotes:
    - name: zephyrproject-rots
      url-base: https://github.com/zephyrproject-rtos
    - name: custom-zephyr
      url-base: https://github.com/helo9
  projects:
    - name: zephyr
      remote: custom-zephyr
      revision: custom_features
      import: true
  self:
    path: frickelflightcontrol
