# Copyright (c) 2022, Jonathan Hahn
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.20.0
    env:
      #CMAKE_PREFIX_PATH: /opt/toolchains
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.13.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: zephly
      - name: Initialize
        working-directory: zephly
        run: |
          pip3 install -U west
          west init -l .
          west update
          west zephyr-export
          pip3 install -r ../zephyr/scripts/requirements-base.txt
      - name: Run Tests
        working-directory: zephly
        run: |
          ../zephyr/scripts/twister -T tests -p native_posix -v
      - name: Build samples
        working-directory: zephly
        run: |
          ../zephyr/scripts/twister -T samples -A boards 
      - name: Build app for openpilot cc3d
        working-directory: zephly
        run: |
          west build --board=openpilot_cc3d app --pristine
